# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Vux Doc And Demos

on:
  push:
    branches: [ "v2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 下载源码
      - name: Checkout
        uses: actions/checkout@v4

      # 打包
      - name: Build routers
        uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: |
          echo $PWD
          yarn install
          yarn run doc:build
      - run: |
          cd docs/
          echo $PWD
          yarn install
          yarn run gen

      # 发布文档
      - name: Push Doc
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages-doc
          publish_dir: docs/.ream/dist

      # 发布示例
      - name: Push Demos
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages-demos
          publish_dir: docs/demos
